-- No-op: event_date has been removed and event_datetime is now the canonical timestamp.
-- For existing databases, migrate manually, for example:
-- ALTER TABLE <table> CHANGE COLUMN event_date_time event_datetime DATETIME NOT NULL;
-- ALTER TABLE <table> DROP COLUMN event_date;
